### ISSUE TITLE
changing error response

### ISSUE THREAD

**Issue by tanneberger** [cryptic-game/cryptic-device#21]
**Describe the bug**
Errors are fucking weird.

**Expected behavior**
Something like: {"error":"error message"} instead of {"ok":False, "error":"error messages"}

**Solution**
change it

**Additional context**
For consistency

**Comment by MaxiHuHe04** [comment]
That’s right. But not only in this repo. We should think of a better error handling system for the whole backend

**Comment by tanneberger** [comment]
Only this repo was using this form so I change it.
