### ISSUE TITLE
a few Bugs

### ISSUE THREAD

**Issue by Haeherfeder** [cryptic-game/cryptic-device#41]
1. Bug: the Terminal dont show the Username@Host
2. Bug: the Terminal dont show the "answer" from the commands: [spot, ls, hostname]

tested browser:[Firefox(with uMatrix),Chrome]
yesterday was it normal/ y hadnt had this bug Yesterday.

an example terminal session

touch test XXXXXX23-XeXc-XXXX-XXXX-XXXXXXXf00db XXXXXXXXXX
morphcoin look test
ls
help

**Comment by felixevers** [comment]
Can you clearify that a little bit more?!

**Comment by tanneberger** [comment]
@Haeherfeder  ^

**Comment by tanneberger** [comment]
@use-to We have this one time bugs pretty often it could be that in our python3 library the connection too the db timed out ... we checked got reloaded but this process was not finished yet so the request failed ... this is very unlikely but could happen

**Comment by felixevers** [comment]
@SpartanerSpaten Ideas to fix this?

**Comment by felixevers** [comment]
I guess a fix is already online! Done.
