### ISSUE TITLE
directory can be moved into itself

### ISSUE THREAD

**Issue by Defelo** [cryptic-game/cryptic-device#94]
**Describe the bug**
Any directory that is directly contained in the root directory of a device can be moved into itself.

**Additional Comments**
https://github.com/cryptic-game/cryptic-device/blob/experimental/app/resources/file.py#L85

**Failing Integration Test**
https://github.com/cryptic-game/integration-tests/blob/dbea37cfa9b45a008e29614c99d590619d5e9466/tests/test_files.py#L406

**Comment by T2brozz** [comment]
hier ich
